### PR TITLE
Upgrade dotnet core IOC resolution to fix default IOC scope problems #53

### PR DESCRIPTION
**Pull request by srpeirce**
Updated a number of services to Singleton from Transient. These were being used by Singletons.

### CODE REVIEW

**Comment by srpeirce** [comment]
Fair question. I don't think there would be...I think the only problem would be if a behaviour had state but then I would question why that behaviour has state. Also, if it did have state I don't think it would be working at the moment anyway - although they are currently Transient because they are being used by Singletons we aren't creating new instances each time they are used.

**Comment by srpeirce** [comment]
Unless @DaveAurionix, @ilivewithian, @AndyRB  think I'm a confused individual? 👍

**Comment by DaveAurionix** [comment]
Hi @srpeirce, sorry I'm very quiet on Pat nowadays, I'm spreading myself quite thin and this project had to be kinda dropped, apologies for that.  Consequently it's best to assume my opinion has very little weight behind it - and don't in any way wait for my opinion before pressing on with any changes you need.

That said, generally I'm keen to avoid transient lifetime objects so agree with the spirit of what you're proposing.  I'm slightly hesitant because I vaguely remember considering a similar change before and realised it wouldn't work, possibly because of dependencies of some behaviours used in the pipeline that have to be resolved in the scope of handling a message so that they are given a MessageContext or something along those lines.  Sorry I can't be more specific.  If you've reviewed these and come to a different conclusion I'm very happy to assume your knowledge is more up-to-date.

I trust the tests would find any problems, although I don't think there are any formal performance tests so issues with data being shared accidentally between different pipeline-executions when singletons are used instead of transient objects (i.e. when handling different messages concurrently) might not be revealed - we might not have tests that deliberately provoke that scenario.

Happy to go with your opinion.

**Comment by DaveAurionix** [comment]
@srpeirce Sorry I've just stopped to check a random behaviour and realised that the next behaviour is passed in as a method argument not a constructor parameter.  We might be OK.

**Comment by srpeirce** [comment]
@DaveAurionix Thanks for the comment - no problem whatsoever - I appreciate you taking the time to reply :) I hope you're doing well mate.

**Pull request merged**
